[build]
  command = "npm run build"
  publish = "dist"
  working_directory = "src/susconnect"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
